export const API_ENDPOINTS = Object.freeze({
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/users/me",
  },
  users: {
    list: "/users",
    detail: (userId: string) => `/users/${userId}`,
    me: "/users/me",
    password: "/users/me/password",
  },
  customers: {
    list: "/customers",
    create: "/customers",
    detail: (customerId: string) => `/customers/${customerId}`,
    update: (customerId: string) => `/customers/${customerId}`,
    activate: (customerId: string) => `/customers/${customerId}/activate`,
    deactivate: (customerId: string) => `/customers/${customerId}/deactivate`,
    history: (customerId: string) => `/customers/${customerId}/maintenance-history`,
  },
  vehicles: {
    list: "/vehicles",
    create: "/vehicles",
    detail: (vehicleId: string) => `/vehicles/${vehicleId}`,
    update: (vehicleId: string) => `/vehicles/${vehicleId}`,
    activate: (vehicleId: string) => `/vehicles/${vehicleId}/activate`,
    deactivate: (vehicleId: string) => `/vehicles/${vehicleId}/deactivate`,
    ownership: (vehicleId: string) => `/vehicles/${vehicleId}/ownership`,
    transferOwnership: (vehicleId: string) => `/vehicles/${vehicleId}/transfer-ownership`,
    history: (vehicleId: string) => `/vehicles/${vehicleId}/maintenance-history`,
  },
  maintenance: {
    list: "/maintenance-cards",
    create: "/maintenance-cards",
    detail: (cardId: string) => `/maintenance-cards/${cardId}`,
    update: (cardId: string) => `/maintenance-cards/${cardId}`,
    close: (cardId: string) => `/maintenance-cards/${cardId}/close`,
    reopen: (cardId: string) => `/maintenance-cards/${cardId}/reopen`,
    works: (cardId: string) => `/maintenance-cards/${cardId}/required-works`,
    work: (cardId: string, workId: string) => `/maintenance-cards/${cardId}/required-works/${workId}`,
    photos: (cardId: string) => `/maintenance-cards/${cardId}/photos`,
    photo: (cardId: string, photoId: string) => `/maintenance-cards/${cardId}/photos/${photoId}`,
    photoContent: (cardId: string, photoId: string) => `/maintenance-cards/${cardId}/photos/${photoId}/content`,
    signature: (cardId: string) => `/maintenance-cards/${cardId}/signature`,
    signatureContent: (cardId: string) => `/maintenance-cards/${cardId}/signature/content`,
    options: (kind: string) => `/maintenance-card-options/${kind}`,
    option: (kind: string, id: string) => `/maintenance-card-options/${kind}/${id}`,
    activateOption: (kind: string, id: string) => `/maintenance-card-options/${kind}/${id}/activate`,
    deactivateOption: (kind: string, id: string) => `/maintenance-card-options/${kind}/${id}/deactivate`,
  },
})
