import { useEffect, useId, useRef, useState } from "react"
import { useTranslation } from "react-i18next"
import { Camera, ImagePlus, PenLine, Trash2, Upload } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { normalizeApiError } from "@/lib/api/api-error"
import { formatDateTime } from "@/lib/formatter"
import { useDeleteMaintenancePhoto, useDeleteMaintenanceSignature, useMaintenancePhotoBlob, useMaintenancePhotos, useMaintenanceSignature, useMaintenanceSignatureBlob, useUploadMaintenancePhotos, useUploadMaintenanceSignature } from "../hooks/useMaintenanceMedia"
import { MAINTENANCE_IMAGE_TYPES, MAX_MAINTENANCE_PHOTO_BYTES, MAX_MAINTENANCE_SIGNATURE_BYTES, MAX_PHOTOS_PER_UPLOAD, type MaintenancePhoto } from "../types/maintenance-media.types"

function useObjectUrl(blob?: Blob) { const [url, setUrl] = useState<string>(); useEffect(() => { if (!blob) { setUrl(undefined); return }; const next = URL.createObjectURL(blob); setUrl(next); return () => URL.revokeObjectURL(next) }, [blob]); return url }
function AuthImage({ blob, alt, className }: { blob?: Blob; alt: string; className: string }) { const url = useObjectUrl(blob); return url ? <img src={url} alt={alt} className={className}/> : <div className={`${className} animate-pulse bg-muted`} aria-label={alt}/> }
function validate(file: File, max: number) { if (!(MAINTENANCE_IMAGE_TYPES as readonly string[]).includes(file.type)) return "unsupportedType"; if (file.size > max) return "fileTooLarge"; return null }

function PhotoTile({ cardId, photo, editable, deleting, remove }: { cardId: string; photo: MaintenancePhoto; editable: boolean; deleting: boolean; remove: () => void }) {
  const { t } = useTranslation("maintenance"); const content = useMaintenancePhotoBlob(cardId, photo.id); const [preview, setPreview] = useState(false)
  const alt = t("media.photos.alt", { name: photo.originalFileName ?? photo.id })
  return <div className="overflow-hidden rounded-lg border bg-card"><button type="button" className="block aspect-video w-full overflow-hidden focus-visible:ring-2 focus-visible:ring-primary" onClick={() => setPreview(true)} aria-label={t("media.photos.previewNamed", { name: photo.originalFileName ?? t("media.photos.photo") })} disabled={!content.data}>{content.isError ? <span className="flex h-full items-center justify-center text-sm text-destructive">{t("media.loadFailed")}</span> : <AuthImage blob={content.data} alt={alt} className="h-full w-full object-cover"/>}</button><div className="flex justify-between gap-2 p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{photo.originalFileName ?? t("media.photos.photo")}</p><p className="text-xs text-muted-foreground">{formatDateTime(photo.createdAt)}</p></div>{editable && <Button type="button" variant="ghost" size="icon" disabled={deleting} aria-label={t("media.photos.delete")} onClick={remove}><Trash2 className="h-4 w-4 text-destructive"/></Button>}</div><Dialog open={preview} onOpenChange={setPreview}><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>{photo.originalFileName ?? t("media.photos.preview")}</DialogTitle><DialogDescription>{t("media.photos.previewDescription")}</DialogDescription></DialogHeader><AuthImage blob={content.data} alt={alt} className="max-h-[75vh] w-full rounded-md object-contain"/></DialogContent></Dialog></div>
}

export function MaintenanceMediaSection({ cardId, open, signaturePresent }: { cardId: string; open: boolean; signaturePresent: boolean }) {
  const { t } = useTranslation("maintenance"); const photoId = useId(); const signatureId = useId(); const photoInput = useRef<HTMLInputElement>(null); const signatureInput = useRef<HTMLInputElement>(null)
  const photos = useMaintenancePhotos(cardId); const uploadPhotos = useUploadMaintenancePhotos(); const deletePhoto = useDeleteMaintenancePhoto(); const signature = useMaintenanceSignature(cardId, signaturePresent); const signatureBlob = useMaintenanceSignatureBlob(cardId, signaturePresent); const uploadSignature = useUploadMaintenanceSignature(); const deleteSignature = useDeleteMaintenanceSignature(); const [error, setError] = useState("")
  const run = async (action: () => Promise<unknown>) => { setError(""); try { await action() } catch (cause) { setError(normalizeApiError(cause).message) } }
  const selectPhotos = (list: FileList | null) => { const files = Array.from(list ?? []); if (!files.length) return; const issue = files.length > MAX_PHOTOS_PER_UPLOAD ? "maximumReached" : files.map(file => validate(file, MAX_MAINTENANCE_PHOTO_BYTES)).find(Boolean); if (issue) { setError(t(`media.errors.${issue}`)); if(photoInput.current) photoInput.current.value = ""; return } void run(async () => { try { await uploadPhotos.mutateAsync({ cardId, files }) } finally { if(photoInput.current) photoInput.current.value = "" } }) }
  const selectSignature = (file?: File) => { if (!file) return; const issue = validate(file, MAX_MAINTENANCE_SIGNATURE_BYTES); if (issue) { setError(t(`media.errors.${issue}`)); if(signatureInput.current) signatureInput.current.value = ""; return } void run(async () => { try { await uploadSignature.mutateAsync({ cardId, file }) } finally { if(signatureInput.current) signatureInput.current.value = "" } }) }
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Camera className="h-4 w-4 text-primary"/>{t("media.title")}</CardTitle></CardHeader><CardContent className="space-y-6">{error && <p role="alert" className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    <section className="space-y-3" aria-labelledby={`${photoId}-title`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id={`${photoId}-title`} className="font-medium">{t("media.photos.title")}</h3><p className="text-sm text-muted-foreground">{t("media.photos.hint")}</p></div>{open && <><input ref={photoInput} id={photoId} type="file" className="sr-only" accept={MAINTENANCE_IMAGE_TYPES.join(",")} multiple onChange={e => selectPhotos(e.target.files)}/><Button type="button" variant="outline" disabled={uploadPhotos.isPending} onClick={() => photoInput.current?.click()}><ImagePlus className="me-2 h-4 w-4"/>{uploadPhotos.isPending ? t("media.uploading") : t("media.photos.add")}</Button></>}</div>{photos.isLoading ? <p className="text-sm text-muted-foreground">{t("loading")}</p> : photos.isError ? <div className="flex gap-2 text-sm text-destructive"><span>{t("media.loadFailed")}</span><Button variant="ghost" size="sm" onClick={() => void photos.refetch()}>{t("media.retry")}</Button></div> : photos.data?.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{photos.data.map(photo => <PhotoTile key={photo.id} cardId={cardId} photo={photo} editable={open} deleting={deletePhoto.isPending} remove={() => { if(window.confirm(t("media.photos.deleteConfirm"))) void run(() => deletePhoto.mutateAsync({ cardId, photoId: photo.id })) }}/>)}</div> : <p className="rounded-md border border-dashed p-6 text-center text-sm text-muted-foreground">{t("media.photos.empty")}</p>}</section>
    <section className="space-y-3 border-t pt-5" aria-labelledby={`${signatureId}-title`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id={`${signatureId}-title`} className="font-medium">{t("media.signature.title")}</h3><p className="text-sm text-muted-foreground">{signaturePresent ? t("media.signature.present") : t("media.signature.empty")}</p></div>{open && <div className="flex gap-2"><input ref={signatureInput} id={signatureId} type="file" className="sr-only" accept={MAINTENANCE_IMAGE_TYPES.join(",")} onChange={e => selectSignature(e.target.files?.[0])}/><Button variant="outline" disabled={uploadSignature.isPending} onClick={() => signatureInput.current?.click()}><Upload className="me-2 h-4 w-4"/>{signaturePresent ? t("media.signature.replace") : t("media.signature.upload")}</Button>{signaturePresent && <Button variant="ghost" disabled={deleteSignature.isPending} onClick={() => { if(window.confirm(t("media.signature.deleteConfirm"))) void run(() => deleteSignature.mutateAsync(cardId)) }}><Trash2 className="me-2 h-4 w-4 text-destructive"/>{t("media.signature.delete")}</Button>}</div>}</div>{signaturePresent && (signature.isError || signatureBlob.isError ? <p className="text-sm text-destructive">{t("media.loadFailed")}</p> : <div className="max-w-xl rounded-lg border bg-white p-4"><AuthImage blob={signatureBlob.data} alt={t("media.signature.alt")} className="max-h-56 w-full object-contain"/>{signature.data && <p className="mt-2 text-xs text-zinc-600">{t("media.signature.size", { size: (Number(signature.data.sizeBytes) / 1024).toFixed(1) })}</p>}</div>)}{!signaturePresent && <div className="flex items-center gap-2 rounded-md border border-dashed p-6 text-sm text-muted-foreground"><PenLine className="h-4 w-4"/>{t("media.signature.empty")}</div>}</section>
  </CardContent></Card>
}
